# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
User.create!(username: "test", email: "test@test.com", password: "password")
User.create!(username: "emanuel", email: "emanuel@test.com", password: "password")
User.create!(username: "random", email: "random@test.com", password: "password")
User.create!(username: "admin", email: "admin@test.com", password: "password")

Game.create!(name: "valheim", price: 19.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg?t=1613147226", description: "Game Description")
Game.create!(name: "League Of Legends", price: 0.00, cover_art: "https://www.theindianwire.com/wp-content/uploads/2020/08/league-of-legends.jpg", description: "Game Description")
Game.create!(name: "Valorant", price: 0.00, cover_art: "https://static.wikia.nocookie.net/valorant/images/8/80/Valorant_Cover_Art.jpg", description: "Game Description")
Game.create!(name: "OUTRIDERS", price: 59.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/subs/504022/header_586x192.jpg?t=1611762226", description: "Game Description")
Game.create!(name: "Breathedge", price: 24.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/apps/738520/header.jpg?t=1614276217", description: "Game Description")

Game.create!(name: "Persona® 5 Strikers", price: 59.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/apps/1382330/header.jpg?t=1614057973", description: "Game Description")
Game.create!(name: "Phasmophobia", price: 13.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg?t=1613740031", description: "Game Description")
Game.create!(name: "Destroy All Humans!", price: 14.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/apps/803330/header.jpg?t=1614105177", description: "Game Description")
Game.create!(name: "Warhammer 40,000: Gladius Complete Edition", price: 124.99, cover_art: "https://cdn.cloudflare.steamstatic.com/steam/bundles/9211/seotwyp6z1yjpflq/header_586x192.jpg?t=1547484533", description: "Game Description")

Genre.create!(name: "Puzzle")
Genre.create!(name: "Platform")
Genre.create!(name: "FPS")
Genre.create!(name: "Maze")
Genre.create!(name: "Quest")
Genre.create!(name: "MOBA")
Genre.create!(name: "RPG")
Genre.create!(name: "Multi Player")
Genre.create!(name: "Singleplayer")
Genre.create!(name: "Free to Play")
Genre.create!(name: "Indie")
Genre.create!(name: "survival")

Review.create!(user_id: 1, game_id: 1, description: " The game is good", rating: 5)
Review.create!(user_id: 2, game_id: 2, description: " Addicting", rating: 5)
Review.create!(user_id: 2, game_id: 3, description: " worse version of cs:go", rating: 2)
Review.create!(user_id: 1, game_id: 2, description: " worse version of dota", rating: 1)
Review.create!(user_id: 4, game_id: 6, description: " Anime the game", rating: 4)
Review.create!(user_id: 4, game_id: 7, description: " My favorite streamer game", rating: 5)
Review.create!(user_id: 4, game_id: 8, description: " Who plays this ?", rating: 1)

System.create!(name: "PlayStation")
System.create!(name: "PlayStation2")
System.create!(name: "PlayStation3")
System.create!(name: "PlayStation4")
System.create!(name: "PlayStation5")
System.create!(name: "Xbox")
System.create!(name: "Xbox 360")
System.create!(name: "Xbox one")
System.create!(name: "Xbox series x")
System.create!(name: "Ninetendo Gamecube")
System.create!(name: "N 64")
System.create!(name: "Ninetendo wii")
System.create!(name: "Ninetendo wii U")
System.create!(name: "Ninetendo Switch")
System.create!(name: "PC")

GameGenre.create!(game_id: 1, genre_id: 12)
GameGenre.create!(game_id: 1, genre_id: 7)
GameGenre.create!(game_id: 2, genre_id: 7)
GameGenre.create!(game_id: 1, genre_id: 9)

GameSystem.create!(game_id: 1, system_id: 15)
GameSystem.create!(game_id: 2, system_id: 15)
GameSystem.create!(game_id: 3, system_id: 15)
GameSystem.create!(game_id: 6, system_id: 8)
GameSystem.create!(game_id: 6, system_id: 4)
GameSystem.create!(game_id: 6, system_id: 15)
